version: '3.1'

services:
  nginx:
    container_name: openresty
    image: openresty/openresty:xenial
    ports:
      - 8181:80
    volumes:
      - ./data:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./lua:/lua:ro